theme: jekyll-theme-minimal
title: Jiwon Choe
logo: me.jpeg
description: >
  PhD candidate.<br>
  Computer Science, Brown University.
  <br><br>
  jiwon_choe [at] brown [dot] edu
  <br>
  Twitter: @jiwonbrownrice
show_downloads: false
github:
  is_user_page: false
