theme: jekyll-theme-minimal
title: Jiwon Choe
logo: me.jpeg
description: >
  jiwon_choe [at] alumni [dot] brown [dot] edu
  <br>
  Twitter: @jiwonbrownrice
show_downloads: false
github:
  is_user_page: false
